"""Create project and detection table

Revision ID: 66f2ffeb91c0
Revises: f86ef0aa7b28
Create Date: 2024-04-26 04:56:34.243796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f2ffeb91c0'
down_revision: Union[str, None] = 'f86ef0aa7b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detections_id', table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datalake_image_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arnes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('barbuquejo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('botas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('casco', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chaleco', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eslingas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guantes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proteccion_auditiva', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proteccion_respiratoria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proteccion_visual', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='detections_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='detections_pkey')
    )
    op.create_index('ix_detections_id', 'detections', ['id'], unique=False)
    # ### end Alembic commands ###
