name: Continuous Integration

on:
  push:
    branches:
      - main  # Asegúrate de usar el nombre de tu rama principal

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Wait for services to be up
      run: |
        sleep 30

    - name: Run tests
      run: docker-compose exec backend pytest tests/detection_ppe.py

    - name: Cleanup
      if: always()
      run: docker-compose down